BetaTesters/Controllers/CandidateApplicationController.cs
using BetaTesters.Core.Contracts;
using BetaTesters.Core.Models.CandidateApplication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using BetaTesters.Attributes;
using static BetaTesters.Infrastructure.Constants.RoleConstants;

namespace BetaTesters.Controllers
{
    public class CandidateApplicationController : BaseController
    {
        private readonly ICandidateApplicationService candidateApplicationService;
        private readonly IApplicationUserService applicationUserService;

        public CandidateApplicationController(ICandidateApplicationService _candidateApplicationService,
            IApplicationUserService _applicationUserService)
        {
            candidateApplicationService = _candidateApplicationService;
            applicationUserService = _applicationUserService;
        }

        [HttpGet]
        [NotSubmittedApplication]
        [Authorize(Roles = DefaultUserRole)]
        public async Task<IActionResult> Add(string id)
        {
            if(id == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId != null)
            {
                return Unauthorized();
            }

            var model = new CandidateApplicationFormModel
            {
                BetaProgramId = id
            };

            return View(model);
        }


        [HttpPost]
        [NotSubmittedApplication]
        [Authorize(Roles = DefaultUserRole)]
        public async Task<IActionResult> Add(CandidateApplicationFormModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            if(model.BetaProgramId == null)
            {
                return BadRequest();
            }

            try
            {
                await candidateApplicationService.CreateAsync(model, User.Id(), model.BetaProgramId);
            }
            catch(Exception)
            {
                GeneralError();
            }

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [HttpGet]
        [Authorize(Roles = DefaultUserRole)]
        public async Task<IActionResult> Mine()
        {
            var userId = User.Id();

            var models = await candidateApplicationService.ApplicationsByUserIdAsync(userId);

            return View(models);
        }

        [HttpGet]
        [IsNotReviewed]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            if (await candidateApplicationService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (candidateApplicationService.GetById(id).CandidateId != Guid.Parse(User.Id()))
            {
                return Unauthorized();
            }

            var model = await candidateApplicationService.GetCandidateApplicationFormModelByIdAsync(id);

            return View(model);
        }

		[HttpPost]
        [IsNotReviewed]
		public async Task<IActionResult> Edit(string id, CandidateApplicationFormModel application)
        {
            if (id == null)
            {
                return BadRequest();
            }

            if (await candidateApplicationService.ExistsAsync(id) == false)
			{
				return BadRequest();
			}

            if (candidateApplicationService.GetById(id).CandidateId != Guid.Parse(User.Id()))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
			{
				return View(application);
			}

			await candidateApplicationService.EditAsync(id, application);

			return RedirectToAction(nameof(Mine));
		}

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            if (candidateApplicationService.GetById(id).CandidateId != Guid.Parse(User.Id()))
            {
                return Unauthorized();
            }

            var application = await candidateApplicationService.CandidateApplicationDetailsByIdAsync(id);

            return View(application);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CandidateApplicationViewModel model)
        {
            if (model == null)
            {
                return BadRequest();
            }

            if (candidateApplicationService.GetById(model.Id.ToString()).CandidateId != Guid.Parse(User.Id()))
            {
                return Unauthorized();
            }

            await candidateApplicationService.DeleteAsync(model.Id.ToString());

            return RedirectToAction(nameof(Mine));
        }

        [HttpGet]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> AllCurrentProgram(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId.ToString() != id)
            {
                return Unauthorized();
            }

            var models = await candidateApplicationService.ApplicationsByProgramIdAsync(id);

            return View(models);
        }

        [HttpGet]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Approve(string id)
        {
            if(id == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            var application = await candidateApplicationService.CandidateApplicationInspectDetailsByIdAsync(id);

            if(user.BetaProgramId != application.BetaProgramId)
            {
                return Unauthorized();
            }
            
            return View(application);
        }

        [HttpPost]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Approve(string candidateId, CandidateApplicationInspectModel model)
        {
            if(model == null || candidateId == null)
            {
                return BadRequest();
            }

            var betaProgramId = model.BetaProgramId.ToString();

            await candidateApplicationService.ApproveApplicationAsync(model.Id.ToString(), candidateId, betaProgramId);

            return RedirectToAction(nameof(Mine), "BetaProgram");
        }

        [HttpGet]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Reject(string id)
        {
            if(id == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            var application = await candidateApplicationService.CandidateApplicationInspectDetailsByIdAsync(id);

            if (user.BetaProgramId != application.BetaProgramId)
            {
                return Unauthorized();
            }

            return View(application);
        }

        [HttpPost]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Reject(CandidateApplicationInspectModel model)
        {
            if (model == null)
            {
                return BadRequest();
            }

            var betaProgramId = model.BetaProgramId.ToString();

            await candidateApplicationService.DeleteAsync(model.Id.ToString());

            return RedirectToAction(nameof(Mine), "BetaProgram");
        }
    }
}

BetaTesters/Controllers/TaskController.cs
using BetaTesters.Core.Contracts;
using BetaTesters.Core.Models.Task;
using static BetaTesters.Infrastructure.Constants.RoleConstants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using BetaTesters.Infrastructure.Data.Enums;
using BetaTesters.Core.Services;
using BetaTesters.Core.Models.CandidateApplication;

namespace BetaTesters.Controllers
{
    public class TaskController : BaseController
    {
        private readonly ITaskService taskService;
        private readonly IApplicationUserService applicationUserService;

        public TaskController(ITaskService _taskService,
            IApplicationUserService _applicationUserService)
        {
            taskService = _taskService;
            applicationUserService = _applicationUserService;

        }

        [HttpGet]
        public async Task<IActionResult> All(string id, [FromQuery] AllTasksQueryModel query)
        {
            if(id == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if (user.BetaProgramId.ToString() != id)
            {
                return Unauthorized();
            }

            var model = await taskService.AllByProgramIdAsync(
                id,
                query.Category,
                query.TaskSorting,
                query.CurrentPage,
                AllTasksQueryModel.TasksPerPage);

            query.TotalTasksCount = model.TotalTasksCount;
            query.Tasks = model.Tasks;
            query.Categories = await taskService.AllCategoriesNameAsync();
            query.BetaProgramId = id;

            if (query.TotalTasksCount == 0)
            {
                ViewBag.TaskCountMessage = "There are no tasks in this program yet!";
            }

            return View(query);
        }

        [HttpGet]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Add(string programId)
        {
            if(programId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId.ToString() != programId)
            {
                return Unauthorized();
            }

            var model = new TaskFormModel()
            {
                ProgramId = programId,
                Categories = await taskService.AllCategoriesAsync()
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Add(TaskFormModel model)
        {
            if (await taskService.CategoryExistsAsync(model.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exits");
            }

            if (model.ProgramId == null)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Beta program does not exits");
            }

            if (!ModelState.IsValid)
            {
                model.Categories = await taskService.AllCategoriesAsync();

                return View(model);
            }

            try
            {
                if (User.IsInRole(OwnerRole))
                {
                    model.Approval = Approval.Accepted;
                    model.TaskState = TaskState.Available;
                    await taskService.CreateAsync(model, User.Id(), DateTime.Now);
                }
                else
                {
                    model.Approval = Approval.ToBeReviewed;
                    model.TaskState = TaskState.ToBeApproved;
                    await taskService.CreateAsync(model, User.Id(), null);
                }
            }
            catch (Exception)
            {
                GeneralError();
            }

            return RedirectToAction(nameof(BetaProgramController.Mine), "BetaProgram");
        }

        [HttpGet]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Edit(string taskId)
        {
            if(taskId == null)
            {
                return BadRequest();
            }

            if(await taskService.ExistsAsync(taskId) == false)
            {
                return BadRequest();
            }

            var task = await taskService.GetTaskFormModelByIdAsync(taskId);

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId != Guid.Parse(task.ProgramId))
            {
                return Unauthorized();
            }

            if(task.TaskState != TaskState.Available || task.Approval != Approval.Accepted)
            {
                return BadRequest();
            }

            if (User.IsInRole(ModeratorRole))
            {
                if(task.CreatorId.ToLower() != User.Id())
                {
                    return Unauthorized();
                }
            }

            return View(task);
        }

        [HttpPost]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Edit(string taskId, TaskFormModel model)
        {
            if (taskId == null)
            {
                return BadRequest();
            }

            if (await taskService.ExistsAsync(taskId) == false)
            {
                return BadRequest();
            }

            var task = await taskService.GetTaskFormModelByIdAsync(taskId);

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if (user.BetaProgramId != Guid.Parse(task.ProgramId))
            {
                return Unauthorized();
            }

            if (task.TaskState != TaskState.Available || task.Approval != Approval.Accepted)
            {
                return BadRequest();
            }

            if (User.IsInRole(ModeratorRole))
            {
                if (task.CreatorId.ToLower() != User.Id())
                {
                    return Unauthorized();
                }
            }

            if (!ModelState.IsValid)
            {
                model.Categories = await taskService.AllCategoriesAsync();
                return View(model);
            }

            await taskService.EditAsync(taskId, model);

            return RedirectToAction(nameof(BetaProgramController.Mine), "BetaProgram");
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> VisitWaitlist(string programId)
        {
            if(programId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if (user.BetaProgramId.ToString() != programId)
            {
                return Unauthorized();
            }

            var tasks = await taskService.TaskWaitListByProgramIdAsync(programId);

            return View(tasks);
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Approve(string taskId)
        {
            if(taskId == null)
            {
                return BadRequest();
            }

            var task = await taskService.TaskInspectViewModelByIdAsync(taskId);

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId != task.BetaProgramId)
            {
                return Unauthorized();
            }

            if (task.Approval != Approval.ToBeReviewed)
            {
                return BadRequest();
            }

            return View(task);
        }

        [HttpPost]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Approve(string taskId, TaskInspectViewModel model)
        {
            if (model == null || taskId == null)
            {
                return BadRequest();
            }

            await taskService.ApproveTaskAsync(taskId);

            return RedirectToAction(nameof(BetaProgramController.Mine), "BetaProgram");
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Reject(string taskId)
        {
            if (taskId == null)
            {
                return BadRequest();
            }

            var task = await taskService.TaskInspectViewModelByIdAsync(taskId);

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if (user.BetaProgramId != task.BetaProgramId)
            {
                return Unauthorized();
            }

            if (task.Approval != Approval.ToBeReviewed)
            {
                return BadRequest();
            }

            return View(task);
        }

        [HttpPost]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Reject(string taskId, TaskInspectViewModel model)
        {
            if (model == null || taskId == null)
            {
                return BadRequest();
            }

            await taskService.RejectTaskAsync(taskId);

            return RedirectToAction(nameof(BetaProgramController.Mine), "BetaProgram");
        }

        [HttpGet]
        [Authorize(Roles = DefaultUserRole)]
        public async Task<IActionResult> Take(string taskId)
        {
            if(taskId == null)
            {
                return BadRequest();
            }

            var task = await taskService.TaskInspectViewModelByIdAsync(taskId);

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if (user.BetaProgramId != task.BetaProgramId)
            {
                return Unauthorized();
            }

BetaTesters/Views/Shared/_BetaProgramFormPartial.cshtml
@model BetaProgramFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Your program name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="What is it about..."></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your fine URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Create" />
            </div>
        </form>
    </div>
</div>

BetaTesters/Views/Shared/_BetaProgramMainMenuPartial.cshtml
@model BetaProgramDataModel
@{
    ViewData["Title"] = "Your Program";
}

<div class="mt-4 p-5 bg-light text-center">
    <h2 class="display-4">Hello, @User.FindFirstValue(CustomClaims.UserFullNameClaim)!</h2>
    @if (User.IsInRole(RoleConstants.OwnerRole))
    {
        <p class="lead mb-1 mt-3"> Welcome to the @Model.Name - you can <b>see all tasks</b>, <b>add a task</b>, <b>see task waitlist</b>, <b>see program details</b>, <b>see applications</b>, <b>see users info</b> and <b>see moderators info</b></p>
    }
    else if (User.IsInRole(RoleConstants.ModeratorRole))
    {
        <p class="lead mb-1 mt-3"> Welcome to the @Model.Name - you can <b>see all tasks</b>, <b>add a task</b>, <b>see program details</b>, <b>see applications</b> and <b>see users info</b> <br />You can also <b>leave</b> the program</p>
    }
    else
    {
        <p class="lead mb-1 mt-3"> Welcome to the @Model.Name - you can <b>see all tasks</b>, <b>your tasks</b> and <b>see program details</b><br />You can also <b>leave</b> the program.</p>
    }
    <hr class="my-4">
    <a asp-area="" asp-controller="Task" asp-action="All" asp-route-id="@Model.Id.ToString()" class="btn btn-primary btn-lg">See All Tasks</a>
    @if (User.IsInRole(RoleConstants.DefaultUserRole))
    {
        <a asp-area="" asp-controller="Task" asp-action="Mine" asp-route-programId="@Model.Id.ToString()" class="btn btn-primary btn-lg">My Tasks</a>
    }
    else
    {
        <a asp-area="" asp-controller="Task" asp-action="Add" asp-route-programId="@Model.Id.ToString()" class="btn btn-primary btn-lg">Add Task</a>
    }
    @if (User.IsInRole(RoleConstants.OwnerRole))
    {
        <a asp-area="" asp-controller="Task" asp-action="VisitWaitlist" asp-route-programId="@Model.Id.ToString()" class="btn btn-primary btn-lg">Task Waitlist</a>
    }
    <span> | </span>
    <a asp-area="" asp-controller="BetaProgram" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-warning btn-lg">Details</a>
    @if (!User.IsInRole(RoleConstants.DefaultUserRole))
    {
        <span> | </span>
        <a asp-area="" asp-controller="CandidateApplication" asp-action="AllCurrentProgram" asp-route-id="@Model.Id.ToString()" class="btn btn-warning btn-lg">Applications</a>
        <a asp-area="" asp-controller="BetaProgram" asp-action="SeeUsersInfo" asp-route-programId="@Model.Id.ToString()" class="btn btn-warning btn-lg">Users Info</a>
    }
    @if (User.IsInRole(RoleConstants.OwnerRole))
    {
        <a asp-area="" asp-controller="BetaProgram" asp-action="SeeModeratorsInfo" asp-route-programId="@Model.Id.ToString()" class="btn btn-warning btn-lg">Moderators Info</a>
    }
    @if (!User.IsInRole(RoleConstants.OwnerRole))
    {
        <span> | </span>
        <a asp-area="" asp-controller="BetaProgram" asp-action="Leave" asp-route-programId="@Model.Id.ToString()" class="btn btn-danger btn-lg">Leave</a>
    }
</div>

BetaTesters/Views/Shared/_BetaProgramPartial.cshtml
@model BetaProgramServiceModel

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="House Image">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h6>Description: <b>@Model.Description</b></h6>
            <br />
            <a asp-controller="BetaProgram" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-success">Details</a>
        </div>
    </div>
</div>

BetaTesters/Views/Shared/_CandidateApplicationFormPartial.cshtml
@model CandidateApplicationFormModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Motivation"></label>
                <textarea asp-for="Motivation" rows="4" class="form-control" placeholder="Your motivation..."></textarea>
                <span asp-validation-for="Motivation" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" placeholder="+359888888888">
                <span asp-validation-for="PhoneNumber" class="small text-danger"></span>
            </div>

            <label asp-for="BetaProgramId" hidden="true"></label>
            <input asp-for="BetaProgramId" hidden="true"/>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Create" />
            </div>
        </form>
    </div>
</div>

BetaTesters/Views/Shared/_CandidateApplicationInspectPartial.cshtml
@model CandidateApplicationInspectModel
@inject IBetaProgramService betaProgramService

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h3><b>From @($"{Model.Candidate.FirstName} {Model.Candidate.LastName}")</b></h3>
            <h4>Motivation: @Model.Motivation</h4>
            <br />
            <h5>Phone number: @Model.PhoneNumber</h5>
            <a asp-controller="CandidateApplication" asp-action="Approve" asp-route-id="@Model.Id.ToString()"
                class="btn btn-success">Approve</a>
            <a asp-controller="CandidateApplication" asp-action="Reject" asp-route-id="@Model.Id.ToString()"
                class="btn btn-danger">Reject</a>
        </div>
    </div>
</div>

BetaTesters/Views/Shared/_CandidateApplicationPartial.cshtml
@model CandidateApplicationViewModel
@inject IBetaProgramService betaProgramService

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h3><b>@(betaProgramService.BetaProgramByIdAsync(Model.BetaProgramId).Result.Name) Application</b></h3>
            <h4>Motivation: @Model.Motivation</h4>
            <br />
            <h5>Your phone number: @Model.PhoneNumber</h5>
@*             This might be deleted later because on approval or rejection the program should be deleted. *@
            @if((int)Model.Approval == 1)
            {
                <h6 class="alert-success">State: Approved</h6>
            }
            else if((int)Model.Approval == 2)
            {
                <h6 class="alert-danger">State: Rejected</h6>
                <a asp-controller="CandidateApplication" asp-action="Delete" asp-route-id="@Model.Id.ToString()"
                   class="btn btn-danger">Delete and send new</a>
            }
            else
            {
                <h6 class="alert-info">State: Not reviewed yet</h6>
                <a asp-controller="CandidateApplication" asp-action="Edit" asp-route-id="@Model.Id.ToString()"
                   class="btn btn-warning">Edit</a>
                <a asp-controller="CandidateApplication" asp-action="Delete" asp-route-id="@Model.Id.ToString()"
                   class="btn btn-danger">Delete</a>
            }
        </div>
    </div>
</div>

BetaTesters/Views/Shared/_TaskMinePartial.cshtml
@model TaskServiceModel
@inject IApplicationUserService applicationUserService

@{
    var contractor = await applicationUserService.GetApplicationUserByIdAsync(Model.ContractorId!);
}

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h5>Description: <b>@Model.Description</b></h5>
            <h6>
                Reward:
                <b>@String.Format("{0:f2}", Model.Reward) EUR</b>
            </h6>
            <p>Assigned on: <b>@Model.AssignDate</b></p>
            <p>Finished on: <b>@(Model.FinishDate ?? "Not Finished")</b></p>
            @if(Model.State == TaskState.InProgress)
            {
                <p>State: <span class="alert-warning fw-bold">@Model.State</span></p>
            }
            else
            {
                <p>State: <span class="alert-success fw-bold">@Model.State</span></p>
            }
            <p>Contractor: @($"{contractor.FirstName} {contractor.LastName}") </p>
            @if (Model.State == TaskState.InProgress)
            {
                <a asp-controller="Task" asp-action="Complete" asp-route-taskId="@Model.Id.ToString()"
                    class="btn btn-info">Complete</a>
                <a asp-controller="Task" asp-action="Forfeit" asp-route-taskId="@Model.Id.ToString()"
                    class="btn btn-danger">Forfeit</a>
            }
            <br />
        </div>
    </div>
</div>

BetaTesters/Views/Shared/_TaskPartial.cshtml
@model TaskServiceModel
@inject IApplicationUserService applicationUserService

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h5>Description: <b>@Model.Description</b></h5>
            <h6>
                Reward:
                <b>@String.Format("{0:f2}", Model.Reward) EUR</b>
            </h6>
            <p>Assigned on: <b>@Model.AssignDate</b></p>
            <p>Finished on: <b>@(Model.FinishDate ?? "Not Finished")</b></p>
            @if(Model.State == TaskState.Available)
            {
                <p>State: <span class="alert-info fw-bold">@Model.State</span></p>
                if (User.IsInRole(RoleConstants.DefaultUserRole))
                {
                    <a asp-controller="Task" asp-action="Take" asp-route-taskId="@Model.Id.ToString()"
                    class="btn btn-info">Take</a>
                }
                else if(User.IsInRole(RoleConstants.ModeratorRole))
                {
                    if (User.Id().ToString() == Model.CreatorId.ToLower())
                    {
                        <a asp-controller="Task" asp-action="Edit" asp-route-taskId="@Model.Id.ToString()"
                        class="btn btn-warning">Edit</a>
                    }
                }
                else
                {
                    <a asp-controller="Task" asp-action="Edit" asp-route-taskId="@Model.Id.ToString()"
                       class="btn btn-warning">Edit</a>
                }
            }
            else if(Model.State == TaskState.InProgress)
            {
                var contractor = await applicationUserService.GetApplicationUserByIdAsync(Model.ContractorId!);
                <p>State: <span class="alert-warning fw-bold">@Model.State</span></p>
                <p>Contractor: @($"{contractor.FirstName} {contractor.LastName}") </p>
                if (User.IsInRole(RoleConstants.DefaultUserRole))
                {
                    if(contractor.Id == Guid.Parse(User.Id()))
                    {
                        <a asp-controller="Task" asp-action="Complete" asp-route-taskId="@Model.Id.ToString()"
                           class="btn btn-info">Complete</a>
                        <a asp-controller="Task" asp-action="Forfeit" asp-route-taskId="@Model.Id.ToString()"
                           class="btn btn-danger">Forfeit</a>
                    }
                }
            }
            else if(Model.State == TaskState.Completed)
            {
                var contractor = await applicationUserService.GetApplicationUserByIdAsync(Model.ContractorId!);
                <p>State: <span class="alert-success fw-bold">@Model.State</span></p>
                <p>Contractor: @($"{contractor.FirstName} {contractor.LastName}") </p>
            }
            <br />
        </div>
    </div>
</div>

BetaTesters/Views/Shared/_TaskWaitListPartial.cshtml
@model TaskInspectViewModel

<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h5>Description: <b>@Model.Description</b></h5>
            <h6>
                Reward:
                <b>@String.Format("{0:f2}", Model.Reward) EUR</b>
            </h6>
            <br />
            <h5>Creator: @($"{Model.Creator.FirstName} {Model.Creator.LastName}")</h5>
            <a asp-controller="Task" asp-action="Approve" asp-route-taskId="@Model.Id.ToString()"
               class="btn btn-success">Approve</a>
            <a asp-controller="Task" asp-action="Reject" asp-route-taskId="@Model.Id.ToString()"
               class="btn btn-danger">Reject</a>
        </div>
    </div>
</div>