BetaTesters/Controllers/BetaProgramController.cs
using BetaTesters.Core.Contracts;
using BetaTesters.Core.Models.ApplicationUserModels;
using BetaTesters.Core.Models.BetaProgram;
using BetaTesters.Infrastructure.Data.Enums;
using BetaTesters.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static BetaTesters.Infrastructure.Constants.RoleConstants;

namespace BetaTesters.Controllers
{
    public class BetaProgramController : BaseController
	{
		private readonly IBetaProgramService betaProgramService;
        private readonly IApplicationUserService applicationUserService;
        private readonly UserManager<ApplicationUser> userManager;

        public BetaProgramController(IBetaProgramService _betaProgramService,
            IApplicationUserService _applicationUserService,
            UserManager<ApplicationUser> _userManager)
        {
            betaProgramService = _betaProgramService;
            applicationUserService = _applicationUserService;
            userManager = _userManager;
        }

        [HttpGet]
		[AllowAnonymous]
        public async Task<IActionResult> All([FromQuery]AllBetaProgramsQueryModel query)
		{
            try
            {
                var model = await betaProgramService.AllAsync(query.CurrentPage, AllBetaProgramsQueryModel.BetaProgramsPerPage);
                query.TotalBetaProgramsCount = model.TotalBetaProgramsCount;
                query.BetaPrograms = model.BetaPrograms;

                return View(query);
            }
            catch (Exception)
            {
                return GeneralError();
            }
		}

        [HttpGet]
        [AllowAnonymous]
		public async Task<IActionResult> Details(string id)
		{
            if (await betaProgramService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            try
            {
                var model = await betaProgramService.BetaProgramDetailsByIdAsync(id);

                return View(model);
            }
            catch (Exception)
            {
                return GeneralError();
            }
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Add()
        {
            if((await applicationUserService.GetApplicationUserByIdAsync(User.Id())).BetaProgramId != null)
            {
                return BadRequest();
            }

            var model = new BetaProgramFormModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Add(BetaProgramFormModel model)
        {
			if (!ModelState.IsValid)
			{
				return View(model);
			}

			try
			{
				string programId = (await betaProgramService.CreateAsync(model)).ToString();

                var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

                await applicationUserService.SetProgramIdAsync(user, programId);
			}
			catch (Exception)
			{
				GeneralError();
			}

			return RedirectToAction(nameof(All));
		}

        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            if (User.IsInRole(AdminRole))
            {
                return Unauthorized();
            }

            var userId = User.Id();

            if ((await applicationUserService.GetApplicationUserByIdAsync(User.Id())).BetaProgramId == null)
            {
                if (User.IsInRole(OwnerRole))
                {
                    ViewBag.DisplayMessage = "You have not created a program yet!";
                }
                else
                {
                    ViewBag.DisplayMessage = "You have not joined a program yet!";
                }
                return View(null);
            }

            var model = await betaProgramService.BetaProgramByUserId(userId);

            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> SeeUsersInfo(string programId)
        {
            if (programId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if (user.BetaProgramId != Guid.Parse(programId))
            {
                return Unauthorized();
            }

            var usersInProgram = await applicationUserService.GetUsersByProgramId(programId);

            return View(usersInProgram);
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> SeeModeratorsInfo(string programId)
        {
            if (programId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId != Guid.Parse(programId))
            {
                return Unauthorized();
            }

            var moderatorsInProgram = await applicationUserService.GetModeratorsByProgramId(programId);

            return View(moderatorsInProgram);
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Promote(string userId)
        {
            if(userId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(userId);

            var owner = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId != owner.BetaProgramId)
            {
                return Unauthorized();
            }

            if (await userManager.IsInRoleAsync(user, ModeratorRole))
            {
                return BadRequest();
            }

            var userToDisplay = applicationUserService.GetApplicationUserViewModelByUser(user);

            return View(userToDisplay);
        }

        [HttpPost]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Promote(string userId, ApplicationUserViewModel model)
        {
            if(model == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(userId);

            await applicationUserService.PromoteUserToModeratorAsync(user);

            return RedirectToAction(nameof(Mine));
        }

        [HttpGet]
        [Authorize(Roles = $"{DefaultUserRole},{ModeratorRole}")]
        public async Task<IActionResult> Leave(string programId)
        {
            if(programId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserWithTasksByIdAsync(User.Id());

            if(user.BetaProgramId != Guid.Parse(programId))
            {
                return BadRequest();
            }

            if (user.Tasks.Any(t => t.State == TaskState.InProgress))
            {
                return BadRequest("You should first complete or forfeit your tasks before leaving!");
            }

            var programDetails = await betaProgramService.BetaProgramDetailsByIdAsync(programId);

            return View(programDetails);
        }

        [HttpPost]
        [Authorize(Roles = $"{DefaultUserRole},{ModeratorRole}")]
        public async Task<IActionResult> Leave(string programId, BetaProgramDetailsServiceModel model)
        {
            if (programId == null)
            {
                return BadRequest();
            }

            await betaProgramService.LeaveAsync(User.Id());

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [HttpGet]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Kick(string userId)
        {
            if(userId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(userId);

            if(await userManager.IsInRoleAsync(user, OwnerRole))
            {
                return Unauthorized();
            }

            if (await userManager.IsInRoleAsync(user, ModeratorRole) && User.IsInRole(ModeratorRole))
            {
                return Unauthorized();
            }

            var kicker = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if (user.BetaProgramId != kicker.BetaProgramId)
            {
                return Unauthorized();
            }

            string userToDisplayRole = (await userManager.GetRolesAsync(user)).First();

            var userToDisplay = applicationUserService.GetApplicationUserViewModelByUser(user);

            userToDisplay.Role = userToDisplayRole;

            return View(userToDisplay);
        }

        [HttpPost]
        [Authorize(Roles = $"{ModeratorRole},{OwnerRole}")]
        public async Task<IActionResult> Kick(string userId, ApplicationUserViewModel model)
        {
            if (model == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(userId);

            await applicationUserService.KickUserFromProgramAsync(user);

            return RedirectToAction(nameof(Mine));
        }
    }
}

BetaTesters/Controllers/PaymentController.cs
using static BetaTesters.Infrastructure.Constants.RoleConstants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BetaTesters.Core.Contracts;
using System.Security.Claims;
using BetaTesters.Core.Models.Payment;

namespace BetaTesters.Controllers
{
    public class PaymentController : BaseController
    {
        private readonly IPaymentService paymentService;
        private readonly IApplicationUserService applicationUserService;

        public PaymentController(IPaymentService _paymentService,
            IApplicationUserService _applicationUserService)
        {
            paymentService = _paymentService;
            applicationUserService = _applicationUserService;
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Create(string userId)
        {
            if(userId == null)
            {
                return BadRequest();
            }

            var user = await applicationUserService.GetApplicationUserByIdAsync(userId);

            var sender = await applicationUserService.GetApplicationUserByIdAsync(User.Id());

            if(user.BetaProgramId != sender.BetaProgramId)
            {
                return Unauthorized();
            }

            var paymentDetails = await paymentService.GetPaymentServiceModelByUserIdAsync(userId);

            return View(paymentDetails);
        }

        [HttpPost]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Create(PaymentServiceModel model)
        {
            if(model.Money == 0)
            {
                return BadRequest("Your payment's amount should be over 0.00 EUR");
            }

            if(!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await paymentService.CreatePaymentAsync(model.ReceiverId.ToString(), User.Id(), model.Money);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [HttpGet]
        [Authorize(Roles = OwnerRole)]
        public async Task<IActionResult> Sent(string ownerId)
        {
            if(ownerId == null)
            {
                return BadRequest();
            }

            if(User.Id() != ownerId)
            {
                return Unauthorized();
            }

            var payments = await paymentService.GetAllSentPaymentsAsync(ownerId);

            return View(payments);
        }

        [HttpGet]
        [Authorize(Roles = $"{DefaultUserRole},{ModeratorRole}")]
        public async Task<IActionResult> Received(string receiverId)
        {
            if (receiverId == null)
            {
                return BadRequest();
            }

            if (User.Id() != receiverId)
            {
                return Unauthorized();
            }

            var payments = await paymentService.GetAllReceivedPaymentsAsync(receiverId);

            return View(payments);
        }
    }
}

BetaTesters/Views/BetaProgram/Add.cshtml
@model BetaProgramFormModel
@{
	ViewBag.Title = "Create your program";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<partial name="_BetaProgramFormPartial" model="@Model" />

@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

BetaTesters/Views/BetaProgram/All.cshtml
@model AllBetaProgramsQueryModel

@{
    ViewBag.Title = "All Beta Programs";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalBetaProgramsCount /
        AllBetaProgramsQueryModel.BetaProgramsPerPage);
}

<div class="row mb-5">
    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="BetaProgram"
           asp-action="All"
           asp-route-currentPage="@previousPage"><<</a>
    </div>

    @{
        var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
        !Model.BetaPrograms.Any();
    }

    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary
           @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="BetaProgram"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)">>></a>
    </div>
</div>

@if (!Model.BetaPrograms.Any())
{
    <h2 class="text-center">No Beta Programs found by the given criteria!</h2>
}

<div class="row" id="program-container">
    @foreach (var program in Model.BetaPrograms)
    {
        <partial name="_BetaProgramPartial" model="@program" />
    }
</div>

BetaTesters/Views/BetaProgram/Details.cshtml
@model BetaProgramDetailsServiceModel
@inject IBetaProgramService betaProgramService
@inject ICandidateApplicationService candidateApplicationService
@inject IApplicationUserService applicatioUserService

@{
    ViewBag.Title = "Beta Program Details";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="container" style="display:inline">
    <div class="row">
        <div class="col-4">
            <img class="card-img-top" style="width: 20rem;"
                 src="@Model.ImageUrl" alt="House Image">
        </div>
        <div class="card col-8 border-0">
            <p style="font-size:25px;"><u>@Model.Name</u></p>
            <p>@Model.Description</p>
            <p>Total users in this program: <b>@Model.TotalParticipants</b></p>
            <p>Total tasks completed: <b>@Model.TotalTasksCompleted</b></p>
            @if(candidateApplicationService.HasApplicationForCurrentUserAndProgram(User.Id(), Model.Id.ToString()))
            {
                <p><b>You have already submitted your application for our program!</b></p>
            }
            else if(await betaProgramService.GetOwnerIdAsync(Model.Id.ToString()) == Guid.Parse(User.Id()))
            {
                <p><b>You are the owner of this program!</b></p>
            }
            else if (User.IsInRole(RoleConstants.OwnerRole))
            {
                <p><b>You are an owner so you can't candidate!</b></p>
            }
            else if (User.IsInRole(RoleConstants.ModeratorRole))
            {
                <p><b>You are a moderator and you have a program so you can't candidate!</b></p>
            }
            else if((await applicatioUserService.GetApplicationUserByIdAsync(User.Id())).BetaProgramId != null)
            {
                <p><b>You have a program so you can't candidate!</b></p>
            }
            else if ((User.IsInRole(RoleConstants.AdminRole)))
            {
                <p><b>You are the Grear Admin so you can't candidate!</b></p>
            }
            else
            {
                <a asp-controller="CandidateApplication" asp-action="Add" asp-route-id="@Model.Id.ToString()" class="btn btn-success">Candidate</a>
            }
            <div class="form-inline">
            </div>
            <p></p>
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Owner Info</h5>
                    <p class="card-text">Email:  @Model.Owner.Email</p>
                    <p class="card-text">Full name: @($"{Model.Owner.FirstName} {Model.Owner.LastName}")</p>
                </div>
            </div>
        </div>
    </div>
</div>

BetaTesters/Views/BetaProgram/Kick.cshtml
@model ApplicationUserViewModel
@{
    if(Model.Role == RoleConstants.DefaultUserRole)
    {
        ViewBag.Title = "Kick user";
    }
    else
    {
        ViewBag.Title = "Kick moderator";
    }
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                @if(Model.Role == RoleConstants.DefaultUserRole)
                {
                    <h3 class="card-title text-center">User: @($"{Model.FirstName} {Model.LastName}")</h3>
                    <p class="mb-0"><strong>Email: </strong>@Model.Email</p>
                    <p>"Are you sure you want to <span class="text-danger mt-3 fw-bold">kick</span> this user from the program?"</p>
                }
                else
                {
                    <h3 class="card-title text-center">Moderator: @($"{Model.FirstName} {Model.LastName}")</h3>
                    <p class="mb-0"><strong>Email: </strong>@Model.Email</p>
                    <p>"Are you sure you want to <span class="text-danger mt-3 fw-bold">kick</span> this moderator from the program?"</p>
                }
            </div>
            <div class="card-footer">
                <form asp-route-userId="@Model.Id.ToString()" method="post">
                    <button type="submit" class="btn btn-danger">Confirm</button>
                    @if(Model.Role == RoleConstants.DefaultUserRole)
                    {
                        <a asp-action="SeeUsersInfo" asp-route-programId="@Model.BetaProgramId" class="btn btn-secondary">Cancel</a>
                    }
                    else
                    {
                        <a asp-action="SeeModeratorsInfo" asp-route-programId="@Model.BetaProgramId" class="btn btn-secondary">Cancel</a>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

BetaTesters/Views/BetaProgram/Leave.cshtml
@model BetaProgramDetailsServiceModel

@{
    ViewBag.Title = "Leave Beta Program";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="container" style="display:inline">
    <div class="row">
        <div class="col-4">
            <img class="card-img-top" style="width: 20rem;"
                 src="@Model.ImageUrl" alt="House Image">
        </div>
        <div class="card col-8 border-0">
            <p style="font-size:25px;"><u>@Model.Name</u></p>
            <p>@Model.Description</p>
            <p>Total users in this program: <b>@Model.TotalParticipants</b></p>
            <p>Total tasks completed: <b>@Model.TotalTasksCompleted</b></p>
            <p>"Are you sure you want to <span class="text-danger mt-3 fw-bold">leave</span> this program?"</p>
            <form asp-route-programId="@Model.Id.ToString()" method="post">
                <button type="submit" class="btn btn-danger">Leave</button>
                <a asp-action="Mine" class="btn btn-secondary">Cancel</a>
            </form>
            <div class="form-inline">
            </div>
            <p></p>
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Owner Info</h5>
                    <p class="card-text">Email:  @Model.Owner.Email</p>
                    <p class="card-text">Full name: @($"{Model.Owner.FirstName} {Model.Owner.LastName}")</p>
                </div>
            </div>
        </div>
    </div>
</div>

BetaTesters/Views/BetaProgram/Mine.cshtml
@model BetaProgramDataModel

@{
    ViewBag.Title = "My Program";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@if(Model != null)
{
    <div class="row">
        <partial name="_BetaProgramMainMenuPartial" model="Model" />
    </div>
}
else
{
    <h3 class="text-center">@ViewBag.DisplayMessage</h3>
}

BetaTesters/Views/BetaProgram/Promote.cshtml
@model ApplicationUserViewModel
@{
    ViewBag.Title = "Promote user";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">User: @($"{Model.FirstName} {Model.LastName}")</h3>
                <p class="mb-0"><strong>Email: </strong>@Model.Email</p>
                <p>"Are you sure you want to <span class="text-success mt-3 fw-bold">promote</span> this user to moderator?"</p>
            </div>
            <div class="card-footer">
                <form asp-route-userId="@Model.Id.ToString()" method="post">
                    <button type="submit" class="btn btn-success">Confirm</button>
                    <a asp-action="SeeUsersInfo" asp-route-programId="@Model.BetaProgramId" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

BetaTesters/Views/BetaProgram/SeeModeratorsInfo.cshtml
@model IEnumerable<ApplicationUserViewModel>

@{
    ViewBag.Title = "All Moderators";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@if (Model.Any())
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th><label>Email</label></th>
                <th><label>Full Name</label></th>
                <th><label>Created Tasks</label></th>
                <th><label>Actions</label></th>
                <th><label></label></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td><label>@user.Email</label></td>
                    <td><label>@($"{user.FirstName} {user.LastName}")</label></td>
                    <td><label>@user.CreatedTasksCount</label></td>
                    <td><a asp-controller="Payment" asp-action="Create" asp-route-userId="@user.Id.ToString()" class="btn btn-info btn-lg">Pay</a></td>
                    <td><a asp-controller="BetaProgram" asp-action="Kick" asp-route-userId="@user.Id.ToString()" class="btn btn-danger btn-lg">Kick</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3 class="text-center">Your program currently has no moderators!</h3>
}

BetaTesters/Views/BetaProgram/SeeUsersInfo.cshtml
@model IEnumerable<ApplicationUserViewModel>

@{
    ViewBag.Title = "All Users";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@if (Model.Any())
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th><label>Email</label></th>
                <th><label>Full Name</label></th>
                <th><label>Completed Tasks</label></th>
                <th><label>In Progress Tasks</label></th>
                <th><label>Money To Transfer</label></th>
                @if (User.IsInRole(RoleConstants.OwnerRole))
                {
                    <th><label></label></th>
                    <th><label>Actions</label></th>
                    <th><label></label></th>
                }
                else
                {
                    <th><label>Actions</label></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td><label>@user.Email</label></td>
                    <td><label>@($"{user.FirstName} {user.LastName}")</label></td>
                    <td><label>@user.CompletedTasksCount</label></td>
                    <td><label>@user.InProgressTasksCount</label></td>
                    <td><label>@String.Format("{0:f2}", user.MoneyToTransfer)</label></td>
                    @if (User.IsInRole(RoleConstants.OwnerRole))
                    {
                        <td><a asp-controller="Payment" asp-action="Create" asp-route-userId="@user.Id.ToString()" class="btn btn-info btn-lg">Pay</a></td>
                        <td><a asp-controller="BetaProgram" asp-action="Promote" asp-route-userId="@user.Id.ToString()" class="btn btn-success btn-lg">Promote</a></td>
                    }
                    <td><a asp-controller="BetaProgram" asp-action="Kick" asp-route-userId="@user.Id.ToString()" class="btn btn-danger btn-lg">Kick</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3 class="text-center">Your program currently has no users!</h3>
}